export interface ZyncSettings {
    startOnLogin: boolean;
    startMinimized: boolean;
    minimizeToTray: boolean;
    closeToTray: boolean;
    showTrayIcon: boolean;
    language: string;
    theme: 'light' | 'dark' | 'system';
    accentColor: string;
    sidebarWidth: number;
    fontScale: number;
    enableAnimations: boolean;
    notificationsEnabled: boolean;
    notificationSound: boolean;
    showBadgeCount: boolean;
    doNotDisturb: boolean;
    dndSchedule: {
        enabled: boolean;
        startHour: number;
        startMinute: number;
        endHour: number;
        endMinute: number;
    };
    downloadPath: string;
    askDownloadLocation: boolean;
    maxConcurrentDownloads: number;
    telemetryEnabled: boolean;
    crashReportingEnabled: boolean;
    clearDataOnQuit: boolean;
    autoCheckUpdates: boolean;
    autoDownloadUpdates: boolean;
    preReleaseChannel: boolean;
    shortcuts: Record<string, string>;
    hardwareAcceleration: boolean;
    developerMode: boolean;
    customApiUrl: string;
    logLevel: 'debug' | 'info' | 'warn' | 'error';
    _settingsVersion: number;
    _firstLaunchDate: string;
    _lastModified: string;
}
export declare const DEFAULT_SETTINGS: ZyncSettings;
export declare function initSettingsStore(): void;
export declare function getAllSettings(): ZyncSettings;
export declare function getSetting<K extends keyof ZyncSettings>(key: K): ZyncSettings[K];
export declare function setSetting<K extends keyof ZyncSettings>(key: K, value: ZyncSettings[K]): void;
export declare function setMultipleSettings(settings: Partial<ZyncSettings>): void;
export declare function resetSettings(): void;
export declare function resetSetting<K extends keyof ZyncSettings>(key: K): void;
export declare function isSettingModified<K extends keyof ZyncSettings>(key: K): boolean;
export declare function setStartOnLogin(enabled: boolean): void;
export declare function getLoginItemStatus(): {
    openAtLogin: boolean;
    wasOpenedAtLogin: boolean;
};
export declare function onSettingChange<K extends keyof ZyncSettings>(key: K, listener: (newValue: ZyncSettings[K], oldValue: ZyncSettings[K]) => void): () => void;
export declare function exportSettings(): string;
export declare function importSettings(json: string): {
    success: boolean;
    imported: number;
    errors: string[];
};
export declare function getSettingsFilePath(): string;
