const { getSafeEnvInt } = require('../utils/safeEnv');

const ARCHITECTURE_CACHE_MAX_ENTRIES = getSafeEnvInt(
  'ARCHITECTURE_CACHE_MAX_ENTRIES',
  10,
  5000,
  100
);

const ARCHITECTURE_CACHE_TTL_MS = getSafeEnvInt(
  'ARCHITECTURE_CACHE_TTL_MS',
  1000,
  24 * 60 * 60 * 1000,
  300000
);

const DELIVERY_CATCHUP_BATCH_SIZE = getSafeEnvInt(
  'DELIVERY_CATCHUP_BATCH_SIZE',
  1,
  100,
  25
);

const DELIVERY_CATCHUP_MAX_BATCHES = getSafeEnvInt(
  'DELIVERY_CATCHUP_MAX_BATCHES',
  1,
  20,
  4
);

module.exports = {
  ARCHITECTURE_CACHE_MAX_ENTRIES,
  ARCHITECTURE_CACHE_TTL_MS,
  DELIVERY_CATCHUP_BATCH_SIZE,
  DELIVERY_CATCHUP_MAX_BATCHES,
};
