export declare const isMacOS: boolean;
export declare const isWindows: boolean;
export declare const isLinux: boolean;
export declare const isFreeBSD: boolean;
export declare const isARM: boolean;
export declare const isX64: boolean;
export declare const isProduction: boolean;
export declare const isDevelopment: boolean;
export type LinuxDesktopEnvironment = 'gnome' | 'kde' | 'xfce' | 'cinnamon' | 'mate' | 'lxde' | 'lxqt' | 'budgie' | 'deepin' | 'pantheon' | 'unity' | 'unknown';
export declare function detectLinuxDesktop(): LinuxDesktopEnvironment;
export type DisplayServer = 'x11' | 'wayland' | 'unknown';
export declare function detectDisplayServer(): DisplayServer;
export interface SystemInfo {
    platform: NodeJS.Platform;
    osRelease: string;
    osType: string;
    arch: string;
    cpuCores: number;
    totalMemory: number;
    freeMemory: number;
    memoryUsagePercent: number;
    uptime: number;
    homeDir: string;
    hostname: string;
    electronVersion: string;
    nodeVersion: string;
    chromeVersion: string;
    v8Version: string;
    appVersion: string;
    linuxDesktop?: LinuxDesktopEnvironment;
    displayServer?: DisplayServer;
}
export declare function getSystemInfo(): SystemInfo;
export declare function getOSDisplayName(): string;
export declare function formatMemory(bytes: number): string;
export declare function isTraySupported(): boolean;
export declare function isNotificationsSupported(): boolean;
export declare function isGlobalShortcutsSupported(): boolean;
