export const DEFAULT_ZYNC_SETTINGS = {
    theme: 'system',
    launchOnStartup: false,
    minimizeToTray: true,
    startMinimized: false,
    language: 'en',
    zoomLevel: 1.0,
    notificationsEnabled: true,
    notificationSound: true,
    notifyWhenFocused: false,
    autoUpdate: true,
    allowPrerelease: false,
    analyticsEnabled: false,
    crashReportsEnabled: true,
    hardwareAcceleration: true,
    logLevel: 'info',
    customCSS: '',
    proxyUrl: '',
};
//# sourceMappingURL=settings.js.map