export declare const SEND_CHANNELS: {
    readonly DOWNLOAD_PLATFORM: "download-platform";
    readonly OPEN_SETTINGS: "open-settings";
    readonly OPEN_EXTERNAL_LINK: "open-external-link";
    readonly COPY_TO_CLIPBOARD: "copy-to-clipboard";
    readonly MINIMIZE_WINDOW: "minimize-window";
    readonly MAXIMIZE_WINDOW: "maximize-window";
    readonly CLOSE_WINDOW: "close-window";
    readonly NOTIFICATION_SHOW: "notification:show";
    readonly NOTIFICATION_CLEAR: "notification:clear";
    readonly APP_RELAUNCH: "app:relaunch";
    readonly FROM_MAIN: "fromMain";
};
export declare const INVOKE_CHANNELS: {
    readonly GET_APP_VERSION: "get-app-version";
    readonly GET_APP_INFO: "get-app-info";
    readonly GET_SYSTEM_THEME: "get-system-theme";
    readonly IS_WINDOW_MAXIMIZED: "is-window-maximized";
    readonly SHOW_SAVE_DIALOG: "show-save-dialog";
    readonly SHOW_OPEN_DIALOG: "show-open-dialog";
    readonly WRITE_FILE: "write-file";
    readonly SETTINGS_GET_ALL: "settings:get-all";
    readonly SETTINGS_GET: "settings:get";
    readonly SETTINGS_SET: "settings:set";
    readonly SETTINGS_RESET: "settings:reset";
    readonly SETTINGS_TOGGLE_LOGIN: "settings:toggle-login-item";
    readonly SETTINGS_LOGIN_STATUS: "settings:get-login-item-status";
    readonly SETTINGS_IMPORT: "settings:import";
    readonly SETTINGS_EXPORT: "settings:export";
    readonly DIALOG_OPEN: "dialog:open";
    readonly DIALOG_MESSAGE: "dialog:message";
    readonly DIALOG_CONFIRM: "dialog:confirm";
    readonly DIALOG_ERROR: "dialog:error";
    readonly DIALOG_OPEN_FILE: "dialog:open-file";
    readonly DIALOG_SAVE_FILE: "dialog:save-file";
    readonly SHELL_OPEN_EXTERNAL: "shell:open-external";
    readonly UPDATER_CHECK: "updater:check";
    readonly UPDATER_DOWNLOAD: "updater:download";
    readonly UPDATER_INSTALL: "updater:install";
    readonly THEME_GET: "theme:get";
    readonly THEME_SET: "theme:set";
    readonly THEME_TOGGLE: "theme:toggle";
    readonly CONTENT_PROTECTION_TOGGLE: "content-protection:toggle";
    readonly CONTENT_PROTECTION_STATE: "content-protection:state";
    readonly SCREENSHOT_CAPTURE: "screenshot:capture";
    readonly SCREENSHOT_SAVE: "screenshot:save";
};
export declare const RECEIVE_CHANNELS: {
    readonly FROM_MAIN: "fromMain";
    readonly SPLASH_CLOSE: "splash:close";
    readonly SPLASH_STATUS: "splash:status";
    readonly SETTINGS_CHANGED: "settings:changed";
    readonly UPDATER_STATUS: "updater:status";
    readonly UPDATER_PROGRESS: "updater:progress";
    readonly NOTIFICATION_CLICKED: "notification:clicked";
    readonly DEEP_LINK_NAVIGATE: "deep-link:navigate";
    readonly THEME_CHANGED: "theme:changed";
};
export type SendChannel = (typeof SEND_CHANNELS)[keyof typeof SEND_CHANNELS];
export type InvokeChannel = (typeof INVOKE_CHANNELS)[keyof typeof INVOKE_CHANNELS];
export type ReceiveChannel = (typeof RECEIVE_CHANNELS)[keyof typeof RECEIVE_CHANNELS];
export type AnyChannel = SendChannel | InvokeChannel | ReceiveChannel;
