export const SEND_CHANNELS = {
    DOWNLOAD_PLATFORM: 'download-platform',
    OPEN_SETTINGS: 'open-settings',
    OPEN_EXTERNAL_LINK: 'open-external-link',
    COPY_TO_CLIPBOARD: 'copy-to-clipboard',
    MINIMIZE_WINDOW: 'minimize-window',
    MAXIMIZE_WINDOW: 'maximize-window',
    CLOSE_WINDOW: 'close-window',
    NOTIFICATION_SHOW: 'notification:show',
    NOTIFICATION_CLEAR: 'notification:clear',
    APP_RELAUNCH: 'app:relaunch',
    FROM_MAIN: 'fromMain',
};
export const INVOKE_CHANNELS = {
    GET_APP_VERSION: 'get-app-version',
    GET_APP_INFO: 'get-app-info',
    GET_SYSTEM_THEME: 'get-system-theme',
    IS_WINDOW_MAXIMIZED: 'is-window-maximized',
    SHOW_SAVE_DIALOG: 'show-save-dialog',
    SHOW_OPEN_DIALOG: 'show-open-dialog',
    WRITE_FILE: 'write-file',
    SETTINGS_GET_ALL: 'settings:get-all',
    SETTINGS_GET: 'settings:get',
    SETTINGS_SET: 'settings:set',
    SETTINGS_RESET: 'settings:reset',
    SETTINGS_TOGGLE_LOGIN: 'settings:toggle-login-item',
    SETTINGS_LOGIN_STATUS: 'settings:get-login-item-status',
    SETTINGS_IMPORT: 'settings:import',
    SETTINGS_EXPORT: 'settings:export',
    DIALOG_OPEN: 'dialog:open',
    DIALOG_MESSAGE: 'dialog:message',
    DIALOG_CONFIRM: 'dialog:confirm',
    DIALOG_ERROR: 'dialog:error',
    DIALOG_OPEN_FILE: 'dialog:open-file',
    DIALOG_SAVE_FILE: 'dialog:save-file',
    SHELL_OPEN_EXTERNAL: 'shell:open-external',
    UPDATER_CHECK: 'updater:check',
    UPDATER_DOWNLOAD: 'updater:download',
    UPDATER_INSTALL: 'updater:install',
    THEME_GET: 'theme:get',
    THEME_SET: 'theme:set',
    THEME_TOGGLE: 'theme:toggle',
    CONTENT_PROTECTION_TOGGLE: 'content-protection:toggle',
    CONTENT_PROTECTION_STATE: 'content-protection:state',
    SCREENSHOT_CAPTURE: 'screenshot:capture',
    SCREENSHOT_SAVE: 'screenshot:save',
};
export const RECEIVE_CHANNELS = {
    FROM_MAIN: 'fromMain',
    SPLASH_CLOSE: 'splash:close',
    SPLASH_STATUS: 'splash:status',
    SETTINGS_CHANGED: 'settings:changed',
    UPDATER_STATUS: 'updater:status',
    UPDATER_PROGRESS: 'updater:progress',
    NOTIFICATION_CLICKED: 'notification:clicked',
    DEEP_LINK_NAVIGATE: 'deep-link:navigate',
    THEME_CHANGED: 'theme:changed',
};
//# sourceMappingURL=channels.js.map