"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _workspace_project_card from './workspace-project-card.bones.json'
import _task_list_item from './task-list-item.bones.json'
import _project_card_grid from './project-card-grid.bones.json'
import _calendar_events_grid from './calendar-events-grid.bones.json'

registerBones({
  "workspace-project-card": _workspace_project_card,
  "task-list-item": _task_list_item,
  "project-card-grid": _project_card_grid,
  "calendar-events-grid": _calendar_events_grid,
} as any)
